version: '3'
services:
  postgres:
    container_name: local-pg
    build: ./image/postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "super-user"
      POSTGRES_PASSWORD: "dummyPass"
      POSTGRES_DB: "app_db"
      DB_URL: "jdbc:postgresql://localhost:5432/app_db"
      DB_USER: "super-user"
      DB_PASSWORD: "dummyPass"
      JWT_SECRET: "this-is-a-secret"